name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run:
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

      - name: Generate documentation with Sphinx
        run: |
          pip install sphinx
          sphinx-quickstart -q -p docs
          sphinx-apidoc -o docs/source src
          sphinx-build -b html docs/source docs/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html